### ISSUE TITLE
Generate Application

### ISSUE THREAD

**Issue by godsmustbcrazy** [tpryan/Apptacular#23] opened 2010-08-12 19:35 UTC
Version : 1.000293
CF Builder Version : 1.0.0 build: 274293
Windows 7

When the application is first generated the default CFC path picked up is not quite right , I believe this is caused because its a Windows directory and not Mac . This can be fixed pretty easily by going and modifying the Apptacular config but as I have reported in Issue 22 http://github.com/tpryan/Apptacular/issues#issue/22 , I am having problems with Apptacular regeneration

Screenshot http://tinypic.com/r/123l0yu/4

**Comment by tpryan** [comment] 2010-08-13 03:25
Would you be willing to send me the .apptacular/config.xml file from 

d:\inetpub\wwwroot\Wayeo_edit\

It will help me write a test to see what the problem is.

**Comment by godsmustbcrazy** [comment] 2010-08-13 15:33
Here is the config file also from the recreated the project . 
http://64.72.142.162/apptacular/config.xml

**Comment by tpryan** [comment] 2010-08-13 19:13
This is really weird. 

Can you write a file in Apptacular/handlers named test.cfm and add this to it:

<cfdump var ="#ExpandPath('/')#"/>

and tell me what you get

**Comment by godsmustbcrazy** [comment] 2010-08-13 19:19
The result for that is 

D:\inetpub\wwwroot\

**Comment by tpryan** [comment] 2010-08-14 01:42
Fixed bug on Windows 7. For some reason, file paths are being calculated with mixed paths. Apptacular couldn't handle it before, now it can.  

Closed by 13bd51dab9d0a4cf28d2ee9a431d729e5b2d1d28

**Closed as completed by tpryan** 2010-08-14 01:42 UTC
